FROM openjdk:8
RUN yum update -y && \
    yum install wget -y
RUN wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /opt/
WORKDIR /opt/
RUN unzip gradle-5.0-bin.zip
RUN rm -f gradle-5.0-bin.zip

RUN mv gradle-5.0 gradle

ENV PATH=$PATH:/opt/gradle/bin/

CMD tail -f /dev/null
